name: "tiny-admin"
mode: "dev" #dev 开发模式，日志打印到控制台，prod  生产模式，日志不打印控制台
port: 3000
version: 1.0.0
start_time: "2025-12-06"  #此日期用于雪花算法
cluster: true   #如果集群部署 cache必须使用redis
host: http://localhost:8080
log:
  level: debug
#  filename: /Volumes/disk01/baizelog/baizelog.log  #默认./log
#  max_size: 200
#  max_age: 30
#  max_backups: 7
datasource:
  type: mysql
  host: 127.0.0.1
  user: root
  password: 123456
  dbname: tiny_admin
  port: 3306
  max_open_conns: 20
  max_idle_conns: 5
  log_level: 4
  show_sql: true
  chartset: utf8
cache:
  type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    db: 0
    pool_size: 100
    timeout: 30
token:
  expire_time: 60
upload_file:
  type: local     #上传地点 本地->local(集群部署需要做硬盘挂载,挂载路径需一直)  亚马逊->s3   移动云->eos  如果不填则默认本地当前目录
  domain_name: http://localhost:8080   #如果本地则填写服务器域名,其他存储桶填写对应域名
  localhost:
    public_path: ./public/
    private_path: ./private/
jwt:
  secret: SJ_Wyz3dmsdbDOkDujOTSSoBjGQP1BMsVnj
  app_name: tiny-admin
  # Elasticsearch 配置
elasticsearch:
  addresses:
    - http://localhost:9200
  # 如果启用了认证，取消下面的注释并填写相应的用户名和密码
  #username: root
  #password: 123456789
  # 如果使用HTTPS并需要验证CA证书，取消下面的注释并填写证书内容
  # ca_cert: |
  #   -----BEGIN CERTIFICATE-----
  #   ... 证书内容 ...
  #   -----END CERTIFICATE-----